### ISSUE TITLE
Feature Request: Support for Amazon ECS Exec to access containers on AWS Fargate and Amazon EC2

### ISSUE THREAD

**Issue by luiszimmermann** [gjbae1212/gossm#57]
AWS has announced a new functionality to access your containers on AWS Fargate and Amazon EC2. ECS Exec leverages [AWS Systems Manager (SSM)](https://aws.amazon.com/systems-manager/), and specifically SSM Session Manager, to create a secure channel between the device you use to initiate the “exec“ command and the target container.

    Announce: https://aws.amazon.com/pt/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/
    Documentation: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html

Thanks in advance and thanks for this great tool

**Comment by tedsmitt** [comment]
Hey @luiszimmermann - this was raised a while ago in https://github.com/gjbae1212/gossm/issues/37. I still believe that there is a good separation of concerns here, simply because of the different layers of abstraction in ECS (Clusters, Services, Tasks, Containers) vs. EC2. You can check out https://github.com/tedsmitt/ecsgo and see if that meets your needs? Happy to discuss further though!

**Comment by luiszimmermann** [comment]
Hey @tedsmitt I understand that now, thanks, will try to use the ecsgo.
